[workspace]
members = [
    "variant-base",
    "runner",
    "variants/zenoh",
    "variants/custom-udp",
    "variants/quic",
    "variants/hybrid",
    "variants/webrtc",
    "variants/websocket",
]
resolver = "2"