run = "udp-all"
runners = ["alice", "bob"]
default_timeout_secs = 60

[[variant]]
name = "custom-udp-1000x100hz"
binary = "target/release/variant-custom-udp.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 1000
  qos = 2
  log_dir = "./logs"

  [variant.specific]
  multicast_group = "239.0.0.1:19500"
  buffer_size = 65536

[[variant]]
name = "custom-udp-100x100hz"
binary = "target/release/variant-custom-udp.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 100
  qos = 2
  log_dir = "./logs"

  [variant.specific]
  multicast_group = "239.0.0.1:19500"
  buffer_size = 65536

[[variant]]
name = "custom-udp-10x100hz"
binary = "target/release/variant-custom-udp.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 10
  qos = 2
  log_dir = "./logs"

  [variant.specific]
  multicast_group = "239.0.0.1:19500"
  buffer_size = 65536

[[variant]]
name = "custom-udp-max"
binary = "target/release/variant-custom-udp.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "max-throughput"
  values_per_tick = 1000
  qos = 2
  log_dir = "./logs"

  [variant.specific]
  multicast_group = "239.0.0.1:19500"
  buffer_size = 65536

