run = "webrtc-all"
runners = ["alice", "bob"]
default_timeout_secs = 90

[[variant]]
name = "webrtc-1000x100hz"
binary = "target/release/variant-webrtc.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 1000
  log_dir = "./logs"

  [variant.specific]
  signaling_base_port = 19980
  media_base_port = 20000

[[variant]]
name = "webrtc-100x100hz"
binary = "target/release/variant-webrtc.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 100
  log_dir = "./logs"

  [variant.specific]
  signaling_base_port = 19980
  media_base_port = 20000

[[variant]]
name = "webrtc-10x100hz"
binary = "target/release/variant-webrtc.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "scalar-flood"
  values_per_tick = 10
  log_dir = "./logs"

  [variant.specific]
  signaling_base_port = 19980
  media_base_port = 20000

[[variant]]
name = "webrtc-max"
binary = "target/release/variant-webrtc.exe"

  [variant.common]
  tick_rate_hz = 100
  stabilize_secs = 2
  operate_secs = 10
  silent_secs = 2
  workload = "max-throughput"
  values_per_tick = 1000
  log_dir = "./logs"

  [variant.specific]
  signaling_base_port = 19980
  media_base_port = 20000
